# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'OCMock', '~> 3.3'

target 'OCMockDemo' do

end

target 'OCMockDemoTests' do

end

target 'OCMockDemoUITests' do

end

